/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const on_registervehicle_Logic = require('./code/on-registervehicle-logic');
const vehicles_on_createroute_Logic = require('./code/vehicles-on-createroute-logic');
const vehicles_on_measurealltelemetry_Logic = require('./code/vehicles-on-measurealltelemetry-logic');

class MaintainanceService extends LCAPApplicationService {
    async init() {


        this.on('RegisterVehicle', async (request) => {
            return await on_registervehicle_Logic(request);
        });

        this.on('CreateRoute', 'Vehicles', async (request) => {
            return await vehicles_on_createroute_Logic(request);
        });

        this.on('MeasureAllTelemetry', async (request) => {
            return await vehicles_on_measurealltelemetry_Logic(request);
        });


        return super.init();
    }
}


module.exports = {
    MaintainanceService
};